### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by ashwinvis** [natj/swm#1]
Great job in putting this together. I was looking for something similar and I hope to implement the same in @fluiddyn's fluidsim package.

Would you be willing to add a LICENSE so that it would be possible to reuse parts of your code?

**Comment by natj** [comment]
Thanks! You should however note that these are all based on gluing various scripts together. Most notably stuff from [shtns](https://bitbucket.org/nschaeff/shtns).

To make everything easy, I would just refer to the [examples/shallow_water.py](https://bitbucket.org/nschaeff/shtns/src/cb96458f56c0b8521e7f92d73545913af783d7d7/examples/shallow_water.py?at=default&fileviewer=file-view-default) and use their license (which I think is GPL variant).
